title: Victor Adedero
logo: data image p.PNG
description: Data Analyst with 2+ years of experience transforming data into actionable insights. Skilled in Microsoft Excel for automation and reporting, SQL for data extraction and analysis, and Power BI for building interactive dashboards.
#google_analytics:
theme: jekyll-theme-minimal
